### PR TITLE
Implementation of the GameRules::CheckWinner() method[s]

### PR DESCRIPTION
**Pull request by JannikWell**
I just implemented the Methods:
-isValidCoord()
-checkWinner()
-checkHorizontalWinner()
-checkVerticalWinner()
-checkLeftToTopWinner()
-checkRightToTopWinner()
in the GameRules Class.

(The isValidCoord() method is temporary and will be replaced later by a similar method in the GameBoard class)

I also updated the class diagram file.

Furthermore, i had to set the method GameBoard::getTokenAt() to public.

The first PR for those new features and changes was closed because there were a few bugs. I fixed them now.

### CODE REVIEW

**Comment by CodingMarco** [comment]
We have to be more consistent with our curly-braces-style. Of course this has always been a controversial topic but I would argue that we should always place curly braces on a new line and never leave them out for a single statement (Tobi said so).

**Comment by JannikWell** [comment]
True. But the automatic formatting sets the brackets like this. @Bennik2000 is it possible to change that automatic formatting?

**Comment by CodingMarco** [comment]
Yes, Tools -> Options -> search for "clang" -> General -> When I paste: Intent, but do not format and ClangFormat execution: Run ClangFormat only for manually invoked formatting commands.

Also set everything in [search for new line] -> C/C++ -> Formatting -> New lines to "Move to a new line"

**Comment by JannikWell** [comment]
Okay. Thank you @CodingMarco. I thought it is a general setting all over the project^^
I will change that right away.

**Comment by Bennik2000** [comment]
Let's discuss the formatting on monday. I already added a clang formatting configuration right at the beginning of the project. It just has to be used ;)

**Pull request merged**
